<?php

namespace GrayLineTourCMSControllers;

defined('GRAYLINE_WORDPRESS_TOURCMS_PLUGIN_EXECUTE') or die("Access Denied.");

class Enquiry extends MainController
{

    public function view()
    {
        $tour_name = (isset($_GET['tour_name']) && !is_array($_GET['tour_name'])) ? urldecode(wp_strip_all_tags($_GET['tour_name'])): "";
        $tour_id = isset($_GET['tour_id']) ? wp_strip_all_tags($_GET['tour_id']): "";
        $return_url = home_url('/enquiry?success=1');
        $problem_url = home_url('/enquiry?fail=1');
        $enq_cat = !empty($tour_name) ? "$tour_name (Tour: $tour_id)" : '';

        $acc_id  = get_option('grayline_tourcms_wp_account_id');
        $enq_key = get_option('grayline_tourcms_wp_enquiry_key');
        $channel_id = get_option('grayline_tourcms_wp_channel');
        $enabled = get_option('grayline_tourcms_wp_enq_enabled') === '1' && $acc_id && $enq_key ? true : false;
        $success = isset($_GET['success'])? $_GET['success'] : "";
        $fail    = isset($_GET['fail'])? $_GET['fail'] : "";

        set_query_var('enabled', $enabled );
        set_query_var('account_id', $acc_id);
        set_query_var('enquiry_key',  $enq_key);
        set_query_var('channel_id', $channel_id);
        set_query_var('return_url', $return_url);
        set_query_var('problem_url', $problem_url);
        set_query_var('tour_name', $tour_name);
        set_query_var('tour_id', $tour_id);
        set_query_var('success', $success);
        set_query_var('fail', $fail);
        set_query_var('enq_cat', $enq_cat);
    }

    public function getCountries($trans = null)
    {
        $trans = $trans === "en" ? null : $trans;
        $prop = $trans ? "countries_$trans" : "countries";

        return $this->$prop;
    }

    // extract from https://stefangabos.github.io/world_countries/

    private $countries_pt = array(
        "Afeganistão",
        "África do Sul",
        "Albânia",
        "Alemanha",
        "Andorra",
        "Angola",
        "Anguila",
        "Antártica",
        "Antígua e Barbuda",
        "Antilhas Holandesas",
        "Arábia Saudita",
        "Argélia ",
        "Armênia",
        "Aruba",
        "Austrália",
        "Azerbaijão ",
        "Bahamas",
        "Bangladesh",
        "Barbados",
        "Barém",
        "Belarus ",
        "Bélgica ",
        "Belize",
        "Benin",
        "Bermuda",
        "Birmânia",
        "Bolívia",
        "Bósnia e Herzegovina",
        "Botswana ",
        "Brasil",
        "Brunei",
        "Bulgária",
        "Burkina Faso ",
        "Burundi",
        "Butão",
        "Cabo verde",
        "Camarões",
        "Camboja ",
        "Canada",
        "Catar",
        "Cazaquistão",
        "Chade",
        "Chile",
        "China",
        "China",
        "Chipre",
        "Colômbia",
        "Comores ",
        "Conco",
        "Costa do Marfim",
        "Costa Rica ",
        "Croácia",
        "Cuba",
        "Dinamarca",
        "Djibuti",
        "Egito",
        "El Salvador",
        "Emirados Árabes",
        "Equador",
        "Eritreia",
        "Eslováquia",
        "Eslovênia",
        "Estados Unidos",
        "Estônia",
        "Etiópia ",
        "Federação dos Estados da Micronésia",
        "Fiji",
        "Filipinas",
        "Finlândia ",
        "França",
        "Gabão",
        "Gâmbia",
        "Gana",
        "Geórgia",
        "Gibraltar",
        "Granada",
        "Grécia ",
        "Groelândia",
        "Guadalupe",
        "Guam",
        "Guatemala",
        "Guiana",
        "Guiné",
        "Guiné Equatorial",
        "Guiné Francesa",
        "Guiné-Bissau",
        "Haiti",
        "Holanda",
        "Honduras",
        "Hong Kong",
        "Hungria",
        "Ilha Bovet",
        "Ilha de Norfolk",
        "Ilha de Santa Lucia",
        "Ilha do Natal",
        "Ilha Reunião",
        "Ilha Santa Helena",
        "Ilhas Aland",
        "Ilhas Cayman",
        "Ilhas Cocos",
        "Ilhas Cook",
        "Ilhas Faroe ",
        "Ilhas Geórgia do Sul e Sandwich do Sul",
        "Ilhas Heard e Ilhas Mcdonalds",
        "Ilhas Maldivas",
        "Ilhas Mariana",
        "Ilhas Marshall",
        "Ilhas Mauricio",
        "Ilhas Pitcairn",
        "Ilhas Salamão",
        "Ilhas Turcas e Caicos",
        "Índia",
        "Indonésia",
        "Iraque",
        "Irlanda",
        "Islândia",
        "Israel",
        "Itália",
        "Jamaica",
        "Japão",
        "Kiribati",
        "Kuwait",
        "Lesoto",
        "Letônia",
        "Líbano",
        "Libéria",
        "Líbia árabe Jamahiriya",
        "Liechtenstein",
        "Lituânia ",
        "Luxemburgo",
        "Macau",
        "Madagascar",
        "Maláui",
        "Mali",
        "Malta",
        "Marrocos",
        "Martinica",
        "Mauritânia",
        "Mayotte ",
        "México",
        "Moçambique",
        "Mônaco",
        "Mongólia",
        "Montserrat ",
        "Namíbia",
        "Nauru",
        "Nepal",
        "Nicarágua",
        "Níger",
        "Nigéria",
        "Niue",
        "Noruega",
        "Nova Caledônia",
        "Nova Zelândia",
        "Omã",
        "Palau",
        "Panamá",
        "Papua-Nova Guiné",
        "Paquistão",
        "Paraguai",
        "Peru",
        "Polinésia Francesa",
        "Polônia",
        "Porto Rico",
        "Portugal",
        "Quênia",
        "Quirguistão",
        "Reino Unido ",
        "República checa",
        "República da Coreia",
        "Republica da Macedônia",
        "Republica da Moldova ",
        "República Democrática Da Coreia ",
        "República Democrática do Congo",
        "República Democrática do Laos ",
        "Republica do Iran",
        "Republica Dominicana ",
        "România",
        "Ruanda",
        "Rússia",
        "Samoa",
        "Samoa americana",
        "San Marino",
        "São Cristóvão e Nevis",
        "São Pedro e Miquelon",
        "São Tomé e Príncipe",
        "São Vicente e Granadinas",
        "Seicheles",
        "Senegal",
        "Serra Leoa",
        "Servia e Montenegro",
        "Singapura",
        "Siri Lanka",
        "Svalbard",
        "Terras Francesas do Sul",
        "Território Britânico no Oceano indico",
        "Território Palestino",
        "Trindade e Tobago",
        "Vaticano",
    );


    private $countries_es = array(
        "AE" => "Emiratos árabes unidos",
        "AF" => "Afganistán",
        "AL" => "Albania",
        "AM" => "Armenia",
        "AO" => "Angola",
        "AR" => "Argentina",
        "AT" => "Austria",
        "AU" => "Australia",
        "AZ" => "Azerbayán",
        "BA" => "Bosnia herzegovina",
        "BB" => "Barbados",
        "BD" => "Bangladesh",
        "BE" => "Bélgica",
        "BF" => "Burkina faso",
        "BG" => "Bulgaria",
        "BH" => "Bahrein",
        "BI" => "Burundi",
        "BJ" => "Benín",
        "BM" => "Bermuda",
        "BN" => "Brunei darussalam",
        "BO" => "Bolivia",
        "BR" => "Brasil",
        "BT" => "Bhutan",
        "BW" => "Botswana",
        "BY" => "Bielorrusia",
        "BZ" => "Belize",
        "CA" => "Canadá",
        "CD" => "Congo, rep. democrática",
        "CF" => "Centro africana, rep.",
        "CG" => "Congo",
        "CH" => "Suiza",
        "CI" => "Costa de marfil",
        "CL" => "Chile",
        "CM" => "Camerún",
        "CN" => "China",
        "CO" => "Colombia",
        "CR" => "Costa rica",
        "CU" => "Cuba",
        "CV" => "Cabo verde",
        "CY" => "Chipre",
        "CZ" => "República checa",
        "DE" => "Alemania",
        "DJ" => "Djibouti",
        "DK" => "Dinamarca",
        "DM" => "Dominica",
        "DO" => "Dominicana rep.",
        "DZ" => "Argelia",
        "EC" => "Ecuador",
        "EE" => "Estonia",
        "EG" => "Egipto",
        "EH" => "Sáhara occidental",
        "ER" => "Eritrea",
        "ES" => "España",
        "ET" => "Etiopía",
        "FI" => "Finlandia",
        "FJ" => "Fiji",
        "FM" => "Micronesia",
        "FR" => "Francia",
        "GA" => "Gabón",
        "GB" => "Reino unido",
        "GD" => "Granada",
        "GE" => "Georgia",
        "GF" => "Guayana francesa",
        "GH" => "Ghana",
        "GL" => "Groenlandia",
        "GM" => "Gambia",
        "GN" => "Guinea",
        "GQ" => "Guinea ecuatorial",
        "GR" => "Grecia",
        "GT" => "Guatemala",
        "GU" => "Guam",
        "GW" => "Guinea-bissau",
        "GY" => "Guayana",
        "HK" => "Hong kong",
        "HN" => "Honduras",
        "HR" => "Croacia",
        "HT" => "Haiti",
        "HU" => "Hungría",
        "ID" => "Indonesia",
        "IE" => "Irlanda",
        "IL" => "Israel",
        "IN" => "India",
        "IQ" => "Iraq",
        "IR" => "Irán",
        "IS" => "Islandia",
        "IT" => "Italia",
        "JM" => "Jamaica",
        "JO" => "Jordania",
        "JP" => "Japón",
        "KE" => "Kenya",
        "KG" => "Kyrgyzstán",
        "KH" => "Camboya",
        "KM" => "Comores",
        "KP" => "Corea del norte",
        "KR" => "Corea del sur",
        "KW" => "Kuwait",
        "KZ" => "Kazajastán",
        "LA" => "Laos",
        "LB" => "Líbano",
        "LI" => "Liechtenstein",
        "LK" => "Sri lanka",
        "LR" => "Liberia",
        "LS" => "Lesoto",
        "LT" => "Lituania",
        "LU" => "Luxemburgo",
        "LV" => "Letonia",
        "LY" => "Libia",
        "MA" => "Marruecos",
        "MC" => "Mónaco",
        "MD" => "Moldovia",
        "ME" => "Montenegro",
        "MG" => "Madagascar",
        "MK" => "Macedonia",
        "ML" => "Mali",
        "MM" => "Myanmar",
        "MN" => "Mongolia",
        "MO" => "Macao",
        "MR" => "Mauritania",
        "MT" => "Malta",
        "MU" => "Mauricio",
        "MV" => "Maldivas",
        "MW" => "Malawi",
        "MX" => "México",
        "MY" => "Malasia",
        "MZ" => "Mozambique",
        "NA" => "Namibia",
        "NC" => "Nueva caledonia",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NI" => "Nicaragua",
        "NL" => "Holanda",
        "NO" => "Noruega",
        "NP" => "Nepal",
        "NZ" => "Nueva zelanda",
        "OM" => "Omán",
        "PA" => "Panamá",
        "PE" => "Perú",
        "PF" => "Polinesia francesa",
        "PG" => "Papua new guinea",
        "PH" => "Filipinas",
        "PK" => "Pakistán",
        "PL" => "Polonia",
        "PR" => "Puerto rico",
        "PS" => "Palestina",
        "PT" => "Portugal",
        "PY" => "Paraguay",
        "QA" => "Qatar",
        "RO" => "Rumanía",
        "RS" => "Serbia",
        "RU" => "Rusia",
        "RW" => "Ruanda",
        "SA" => "Arabia saudita",
        "SC" => "Seychelles",
        "SD" => "Sudán",
        "SE" => "Suecia",
        "SG" => "Singapur",
        "SI" => "Eslovenia",
        "SK" => "Eslovaquia",
        "SL" => "Sierra leona",
        "SM" => "San marino",
        "SN" => "Senegal",
        "SO" => "Somalia",
        "SR" => "Surinam",
        "ST" => "Sao tome and principe",
        "SV" => "El salvador",
        "SY" => "Siria",
        "SZ" => "Swazilandia",
        "TD" => "Chad",
        "TG" => "Togo",
        "TH" => "Tailandia",
        "TJ" => "Tajikistán",
        "TM" => "Turkmenistán",
        "TN" => "Túnez",
        "TO" => "Tonga",
        "TP" => "Timor Este",
        "TR" => "Turquía",
        "TT" => "Trinidad tobago",
        "TV" => "Tuvalu",
        "TW" => "Taiwán",
        "TZ" => "Tanzania",
        "UA" => "Ucrania",
        "UG" => "Uganda",
        "US" => "Estados unidos",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistán",
        "VA" => "Vaticano",
        "VE" => "Venezuela",
        "VN" => "Vietnám",
        "VU" => "Vanuatú",
        "WS" => "Samoa",
        "YE" => "Yemen",
        "ZA" => "Sud áfrica",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
    );

    private $countries_it = array(
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AG" => "Antigua e Barbuda",
        "SA" => "Arabia Saudita",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaigian",
        "BS" => "Bahamas",
        "BH" => "Bahrein",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BE" => "Belgio",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BT" => "Bhutan",
        "BY" => "Bielorussia",
        "MM" => "Birmania",
        "BO" => "Bolivia",
        "BA" => "Bosnia ed Erzegovina",
        "BW" => "Botswana",
        "BR" => "Brasile",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambogia",
        "CM" => "Camerun",
        "CA" => "Canada",
        "CV" => "Capo Verde",
        "TD" => "Ciad",
        "CL" => "Cile",
        "CN" => "Cina",
        "CY" => "Cipro",
        "CO" => "Colombia",
        "KM" => "Comore",
        "KP" => "Corea del Nord",
        "KR" => "Corea del Sud",
        "CI" => "Costa d'Avorio",
        "CR" => "Costa Rica",
        "HR" => "Croazia",
        "CU" => "Cuba",
        "DK" => "Danimarca",
        "DM" => "Dominica",
        "EC" => "Ecuador",
        "EG" => "Egitto",
        "SV" => "El Salvador",
        "AE" => "Emirati Arabi Uniti",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Etiopia",
        "FJ" => "Figi",
        "PH" => "Filippine",
        "FI" => "Finlandia",
        "FR" => "Francia",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germania",
        "GH" => "Ghana",
        "JM" => "Giamaica",
        "JP" => "Giappone",
        "DJ" => "Gibuti",
        "JO" => "Giordania",
        "GR" => "Grecia",
        "GD" => "Grenada",
        "GT" => "Guatemala",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GQ" => "Guinea Equatoriale",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HN" => "Honduras",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Irlanda",
        "IS" => "Islanda",
        "MH" => "Isole Marshall",
        "SB" => "Isole Salomone",
        "IL" => "Israele",
        "IT" => "Italia",
        "KZ" => "Kazakistan",
        "KE" => "Kenya",
        "KG" => "Kirghizistan",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "LA" => "Laos",
        "LS" => "Lesotho",
        "LV" => "Lettonia",
        "LB" => "Libano",
        "LR" => "Liberia",
        "LY" => "Libia",
        "LI" => "Liechtenstein",
        "LT" => "Lituania",
        "LU" => "Lussemburgo",
        "MK" => "Macedonia del Nord",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldive",
        "ML" => "Mali",
        "MT" => "Malta",
        "MA" => "Marocco",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "MX" => "Messico",
        "FM" => "Micronesia",
        "MD" => "Moldavia",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MZ" => "Mozambico",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NO" => "Norvegia",
        "NZ" => "Nuova Zelanda",
        "OM" => "Oman",
        "NL" => "Paesi Bassi",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PA" => "Panama",
        "PG" => "Papua Nuova Guinea",
        "PY" => "Paraguay",
        "PE" => "Perù",
        "PL" => "Polonia",
        "PT" => "Portogallo",
        "MC" => "Monaco",
        "QA" => "Qatar",
        "GB" => "Regno Unito",
        "CD" => "RD del Congo",
        "CZ" => "Rep. Ceca",
        "CF" => "Rep. Centrafricana",
        "CG" => "Rep. del Congo",
        "DO" => "Rep. Dominicana",
        "RO" => "Romania",
        "RW" => "Ruanda",
        "RU" => "Russia",
        "KN" => "Saint Kitts e Nevis",
        "LC" => "Saint Lucia",
        "VC" => "Saint Vincent e Grenadine",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "São Tomé e Príncipe",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SY" => "Siria",
        "SK" => "Slovacchia",
        "SI" => "Slovenia",
        "SO" => "Somalia",
        "ES" => "Spagna",
        "LK" => "Sri Lanka",
        "US" => "Stati Uniti",
        "ZA" => "Sudafrica",
        "SD" => "Sudan",
        "SS" => "Sudan del Sud",
        "SR" => "Suriname",
        "SE" => "Svezia",
        "CH" => "Svizzera",
        "SZ" => "Swaziland",
        "TJ" => "Tagikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailandia",
        "TL" => "Timor Est",
        "TG" => "Togo",
        "TO" => "Tonga",
        "TT" => "Trinidad e Tobago",
        "TN" => "Tunisia",
        "TR" => "Turchia",
        "TM" => "Turkmenistan",
        "TV" => "Tuvalu",
        "UA" => "Ucraina",
        "UG" => "Uganda",
        "HU" => "Ungheria",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
    );

    private $countries = array(
        "AF" => "Afghanistan",
        "AX" => "Aland Islands",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua And Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia And Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "IO" => "British Indian Ocean Territory",
        "BN" => "Brunei Darussalam",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CV" => "Cape Verde",
        "CI" => "CÃ¢te D'ivoire",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos (keeling) Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo",
        "CD" => "Congo, The Democratic Republic Of The",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands (malvinas)",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GN" => "Guinea",
        "GW" => "Guinea-bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island And Mcdonald Islands",
        "VA" => "Holy See (vatican City State)",
        "HN" => "Honduras",
        "HK" => "Hong Kong",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran Islamic Republic Of",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KP" => "Korea Democratic People\'s Republic Of",
        "KR" => "Korea Republic Of",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Lao People\'s Democratic Republic",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libyan Arab Jamahiriya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macao",
        "MK" => "Macedonia, The Former Yugoslav Republic Of",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "MX" => "Mexico",
        "FM" => "Micronesia, Federated States Of",
        "MD" => "Moldova, Republic Of",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territory, Occupied",
        "PA" => "Panama",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RE" => "Reunion",
        "RO" => "Romania",
        "RU" => "Russia",
        "RW" => "Rwanda",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts And Nevis",
        "LC" => "Saint Lucia",
        "PM" => "Saint Pierre And Miquelon",
        "VC" => "Saint Vincent And The Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "Sao Tome And Principe",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "CS" => "Serbia And Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia And The South Sandwich Islands",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard And Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "TW" => "Taiwan Province Of China",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad And Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks And Caicos Islands",
        "TV" => "Tuvalu",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" => "United States",
        "UM" => "United States Minor Outlying Islands",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "VG" => "Virgin Islands British",
        "VI" => "Virgin Islands U.s.",
        "WF" => "Wallis And Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
    );

}
